# dataset
musdbhq: "../musdb18hq"
musdb: "../musdb18"
wav:

metadata: "../metadata"

# audio params
sources:
  - drums
  - bass
  - other
  - vocals
samplerate: 44100
audio_channels: 2
segment: 11
shift: 1
normalize: true
full_cv: true
train_valid: false

# augument
augment: true
repitch: 0.2
max_tempo: 12
remix_group_size: 4
