# dataset
raw:
  path:
musdb:
  path: "../musdb18"
  is_wav: false
  metadata: "../metadata"
wav:
  path:
  concat: true

# audio params
sources:
  - drums
  - bass
  - other
  - vocals
samplerate: 44100
audio_channels: 2
segment: 11
shift: 1
norm_wav: true

# augument
augment: true
repitch: 0.2
max_tempo: 12
remix_group_size: 4
