defaults:
  - _self_
  - outdir: default
  - device: default
  - dataset: default
  - model/generator: demucs
  - model/discriminator: parallel_wavegan
  - loss: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

# Training option
restart: false
seed: 42
epochs: 180
repeat: 2
batch_size: 64
batch_divide: 1
lr: 0.0003
split_valid: false

# Other options
show: false # Show model architecture, size and exit
save: false # Save estimated for the test set waveforms
save_model: false # Skip traning, just save final model for the current checkpoint value.
save_state: false # Skip training, just save state for the current checkpoint value. You should provide a model name as argument.
half: false # When saving the model, uses half precision.

# Quantization options
q-min-size: 1 # Only quantize layers over this size (in MB)
qat: # If provided, use QAT training with that many bits.
diffq: 0
ms_target: 162 # Model size target in MB, when using DiffQ. Best model will be kept only if it is smaller than this target.

# hydra + optuna
hydra:
  run:
    dir: ../out/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ../out/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: demucs
    storage: null
    n_trials: 10
    n_jobs: 1
# num:
#   example1: 1
#   example2: 2
# name: ${num.example1}_${num.example2}
