# Auxiliary Loss
l1:
  lambda: 1

mse:
  lambda: 0

stft:
  lambda: 0
  params:
    fft_sizes: [1024, 2048, 512] # List of FFT size for STFT-based loss.
    hop_sizes: [120, 240, 50] # List of hop size for STFT-based loss
    win_lengths: [600, 1200, 240] # List of window length for STFT-based loss.
    window: "hann_window" # Window function for STFT-based loss

# Adversarial Loss
adversarial:
  lambda: 0
  generator_params:
    average_by_discriminators: true # Whether to average loss by #discriminators.
    average_by_scales: false # Whether to average loss by #scales.
    loss_type: "mse"
  discriminator_params:
    average_by_discriminators: true # Whether to average loss by #discriminators.
    average_by_scales: false # Whether to average loss by #scales.
    loss_type: "mse"
  train_start_epoch: -1 # 30
